version: '3'
services:
  php-apache:
    image: php:7.2.1-apache
    build:
      context: ./docker/php-apache
    ports:
      - 1080:80
    volumes:
      - .:/var/www/html
    links:
      - 'mariadb'

  mariadb:
    image: mariadb:10.1
    volumes:
      - docker-db:/var/lib/mysql
    ports:
      - 3310:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: 'docker'
      MYSQL_PASSWORD: 'docker'
      MYSQL_DATABASE: 'docker'

volumes:
  docker-db:
